services:
  router_a:
    build:
      context: ./router
      dockerfile: Dockerfile
    image: router
    command: sh -c "sleep infinity"
    container_name: router_a
    cap_add:
      - NET_ADMIN
    networks:
      net-a:
        ipv4_address: 172.16.1.2
      link-a-b:
        ipv4_address: 172.16.60.2

  router_b:
    image: router
    command: sh -c "sleep infinity"
    container_name: router_b
    cap_add:
      - NET_ADMIN
    networks:
      link-a-b:
        ipv4_address: 172.16.60.3
      link-b-c:
        ipv4_address: 172.16.61.2
      net-b:
        ipv4_address: 172.16.100.2

  router_c:
    image: router
    command: sh -c "sleep infinity"
    container_name: router_c
    cap_add:
      - NET_ADMIN
    networks:
      net-c:
        ipv4_address: 172.16.200.2
      link-b-c:
        ipv4_address: 172.16.61.3

  pc_a:
    image: router
    command: sh -c "sleep infinity"
    container_name: pc_a
    cap_add:
      - NET_ADMIN
    networks:
      net-a:
        ipv4_address: 172.16.1.100

  pc_c:
    image: router
    command: sh -c "sleep infinity"
    container_name: pc_c
    cap_add:
      - NET_ADMIN
    networks:
      net-c:
        ipv4_address: 172.16.200.100

networks:
  net-a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

  net-b:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24

  net-c:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.200.0/24

  link-a-b:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.60.0/29

  link-b-c:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.61.0/29
