services:
  router_a:
    build:
      context: ./router
      dockerfile: Dockerfile
    image: router
    # image: busybox # iptables 미포함
    # image: debian
    command: sh -c "sleep infinity"
    container_name: router_a
    cap_add: # 네트워크 설정 허용
      - NET_ADMIN
    networks:
      link-host-a:
        ipv4_address: 172.16.0.2
      link-a-b:
        ipv4_address: 172.16.1.2
      net-a:
        ipv4_address: 172.16.100.2

  router_b:
    # image: busybox
    image: router
    command: sh -c "sleep infinity"
    container_name: router_b
    cap_add:
      - NET_ADMIN
    networks:
      link-a-b:
        ipv4_address: 172.16.1.3
      net-b:
        ipv4_address: 172.16.200.2

  pc_a:
    image: busybox
    command: sh -c "sleep infinity"
    container_name: pc_a
    cap_add:
      - NET_ADMIN
    networks:
      net-a:
        ipv4_address: 172.16.100.3

  pc_b:
    build:
      context: ./python
      dockerfile: Dockerfile
    # image: python:3
    container_name: pc_b
    # command: python3 -m http.server 80
    cap_add:
      - NET_ADMIN
    networks:
      net-b:
        ipv4_address: 172.16.200.3

networks:
  link-host-a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

  link-a-b:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

  net-a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
  net-b:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.200.0/24
